Sync production configuration defaults
This change update config-repo defaults.

Change-Id: I8299e64937a922a4b100ff86a957ced62547e896

diff --git a/puppet/modules/managesf/templates/sf_jjb_conf.yaml.erb b/puppet/modules/managesf/templates/sf_jjb_conf.yaml.erb
--- a/puppet/modules/managesf/templates/sf_jjb_conf.yaml.erb
+++ b/puppet/modules/managesf/templates/sf_jjb_conf.yaml.erb
@@ -34,6 +34,9 @@
     name: rdo-prepare
     builders:
       - shell: |
+          export PATH=/bin:/sbin:/usr/local/bin:/usr/local/sbin
+          sudo yum update -y
+          sudo yum install -y python-croniter # tmp fix for BZ#1293961
           sudo packstack --allinone --os-swift-install=y --os-ceilometer-install=n --nagios-install=n \
                 --provision-demo=n --keystone-admin-passwd=sf4ever --os-heat-install=y --cinder-volumes-size=50G
 
@@ -44,7 +47,9 @@
           export OS_REGION_NAME=RegionOne
 
           echo "[+] Prepare external network provider"
-          sudo openstack-config --set /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini ovs bridge_mappings extnet:br-ex
+          ovs_conf=/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
+          [ -f ${ovs_conf} ] || ovs_conf=/etc/neutron/plugins/ml2/openvswitch_agent.ini
+          sudo openstack-config --set ${ovs_conf} ovs bridge_mappings extnet:br-ex
           sudo openstack-config --set /etc/neutron/plugin.ini ml2 type_drivers vxlan,flat,vlan
           sudo service neutron-openvswitch-agent restart
           sudo service neutron-server restart
@@ -61,7 +66,13 @@
           sudo systemctl restart openstack-nova-compute
 
           echo "[+] Create network"
-          neutron net-create external_network --provider:network_type flat --provider:physical_network extnet --router:external > /dev/null
+          neutron net-create external_network --provider:network_type flat --provider:physical_network extnet --router:external \
+            > /dev/null || {
+                echo "Can't create network..."
+                neutron net-list
+                echo "Continuing on dirty system..."
+                set +e
+          }
           neutron subnet-create --name public_subnet --enable_dhcp=False \
                 --allocation-pool=start=192.168.42.10,end=192.168.42.200 \
                 --gateway=192.168.42.1 external_network 192.168.42.0/24 > /dev/null
@@ -71,7 +82,9 @@
 
           echo "[+] Install cirros"
           wget http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img &> /dev/null
-          glance image-create --name=cirros --is-public=true --container-format=bare --disk-format=qcow2 < cirros-0.3.4-x86_64-disk.img > /dev/null
+          public_param="--is-public=true"
+          glance help image-create | grep -q "is-public" || public_param="--visibility=public"
+          glance image-create --name=cirros ${public_param} --container-format=bare --disk-format=qcow2 < cirros-0.3.4-x86_64-disk.img > /dev/null
 
           echo "[+] Create 3 tenants"
           (for tenantname in sfmain sfnodepool sfswift; do
@@ -102,6 +115,7 @@
             echo "[+] Create Keypairs"
             nova keypair-add --pub-key ~/.ssh/id_rsa.pub id_rsa
           done) > /dev/null
+          set -e
 
 - builder:
     name: rdo-check
