Add a dumb retry function in edeploy/functions
Some tools like pip, gem, git clone does not provide
a retry mechasim in case of network failure. This patch
comes with a dumb retry function in order to make
the SF build more resilient.

Change-Id: Iebdabb477b775092d70680f0d6e99c930a97a3af

diff --git a/edeploy/functions b/edeploy/functions
--- a/edeploy/functions
+++ b/edeploy/functions
@@ -49,4 +49,15 @@ function disable_selinux {
     fi
 }
 
+function retry {
+    # This is a really dumb retry function
+    local max_retries=3
+    local delay=3
+    for i in $(seq $max_retries); do
+        $@ && break
+        echo "The command return $? as error code. Retry (attempt $i) ..."
+        sleep $delay
+    done
+}
+
 . ${ORIG}/functions
