SF-init: Bootstrap config repository via the managesf resource endpoint
- resources.sh now supports the direct_apply action
- config repo creation done by the direct_apply machanism
  in sf_initialize.yml

Depends-on: I61c104b33cdfa78a7ff8ee9880a17255731d768b
Change-Id: I3c1c106d3eb71640260311213eaf8eeec32cdbb4

diff --git a/config/ansible/roles/sf-jenkins/templates/resources.sh.j2 b/config/ansible/roles/sf-jenkins/templates/resources.sh.j2
--- a/config/ansible/roles/sf-jenkins/templates/resources.sh.j2
+++ b/config/ansible/roles/sf-jenkins/templates/resources.sh.j2
@@ -18,8 +18,25 @@ ENDPOINT="http://$FQDN/manage/resources/"
 trap "rm -f $COOKIE_PATH && rm -f $VALIDATED_OUTPUT && rm -f $APPLIED_OUTPUT" EXIT
 
 [ -z "$1" ] && {
-    echo "Valable arguments are validate, apply, get. Exit."
+    echo "Valid arguments are validate, apply, direct_apply, get. Exit."
     exit 1
+}
+
+[ "$1" == "direct_apply" ] && {
+    [ ! -f "$2" -a ! -f "$3" ] && {
+        echo "direct_apply action needs two yaml files as second and third args"
+        echo "$(basename $0) direct_apply prev.yaml new.yaml"
+        exit 1
+    } || {
+        rm -f direct_apply.json
+        python <<SCRIPT
+import json
+data = {}
+data['prev'] = file("$2").read()
+data['new'] = file("$3").read()
+json.dump(data, file('direct_apply.json', 'w'))
+SCRIPT
+    }
 }
 
 curl -s -X POST -c $COOKIE_PATH --data \
@@ -52,6 +69,18 @@ case $1 in
         cat $APPLIED_OUTPUT | python -m json.tool
         [ "$http_code" != "201" ] && {
             echo "Resource modifications apply failed (API return code: $http_code)."
+            exit 1
+        }
+        exit 0
+        ;;
+    direct_apply)
+        http_code=$(curl -s -w "%{http_code}" -b $COOKIE_PATH \
+         -H "Content-Type: application/json" \
+         --data @direct_apply.json \
+         -X PUT $ENDPOINT -o $APPLIED_OUTPUT)
+        cat $APPLIED_OUTPUT | python -m json.tool
+        [ "$http_code" != "201" ] && {
+            echo "Resource modifications direct_apply failed (API return code: $http_code)."
             exit 1
         }
         exit 0
