image: merge step1 and step2
This change removes the need to manage a cache.
Historically image building uses that 2 steps process because:
* optimize build time of non packaged component in the cache
* the step2 is idempotent (untracked /usr/local/bin/ scripts and
  edeploy trickery...)

With the new zuul-rpm-build process being developped this is not
useful anymore since components are updated using packaging only.
Moreover it turns out that copying the cache to the step2 takes
more time to rebuild the cache each time.

However note that merging this now has the following side-effects:

* non packaged component that are installed only if a directory
  doesn't exists won't be updated. The install function needs to
  take care of update, preferably using newly created packages.
* some cleaning task that are re-performed at the begining at
  the begining of the build are disabled (such as removing build
  requirements)

Change-Id: I19b644a8c19dc3ac9e2da07aaad38ff91f2157ec

diff --git a/image/softwarefactory.install b/image/softwarefactory.install
--- a/image/softwarefactory.install
+++ b/image/softwarefactory.install
@@ -18,7 +18,9 @@
 
 set -e
 
-INSTALL_OPTIONS="--disablerepo=base,epel,extras,updates,jenkins,passenger --enablerepo=sfbase,sfextras,sfupdates,sfepel,sfrdo,sfjenkins,sfpassenger"
+ENABLED_REPO="sfbase,sfextras,sfupdates,sfepel,sfrdo,sfjenkins,sfpassenger,release"
+[ -f /etc/yum.repos.d/zuul-built.repo ] && grep -q testing /etc/yum.repos.d/zuul-built.repo && ENABLED_REPO+=",testing"
+INSTALL_OPTIONS="--disablerepo=* --enablerepo=${ENABLED_REPO}"
 
 [ -z "$DEBUG" ] || set -x
 # Target dir where the centos images will be built
@@ -103,6 +105,7 @@ baseurl=http://46.231.132.68:8080/v1/AUTH_b50e80d3969f441a8b7b1fe831003e0a/rpms
 gpgcheck=0
 enabled=1
 EOF
+
     mkdir -p ${dir}/etc/pki/rpm-gpg/
     rsync -a --delete ${ORIG}/keys/ ${dir}/etc/pki/rpm-gpg/
 
@@ -117,15 +120,19 @@ EOF
 
     # Add the SF repo mirror
     cp /etc/yum.repos.d/sf-mirror.repo ${target}/etc/yum.repos.d/
+    [ -f /etc/yum.repos.d/zuul-built.repo ] && cp /etc/yum.repos.d/zuul-built.repo ${target}/etc/yum.repos.d/
 
     cp -f /etc/resolv.conf ${target}/etc/
+
+    [ -f ${target}/etc/hosts ] && [ "$(grep koji.softwarefactory-project.io ${target}/etc/hosts)" == "" ] && \
+        grep koji.softwarefactory-project.io /etc/hosts | sudo tee -a ${target}/etc/hosts > /dev/null || true
 
     if [ ! -f "${target}/usr/bin/yum" ]; then
         rpm --root="$target" --import $(ls $target/etc/pki/rpm-gpg/*.key | fgrep -v Debug)
         # We cannot use install_packages since the basesystem isn't yet setup
         yum --disableplugin=* --installroot $target $INSTALL_OPTIONS install -y basesystem yum shadow-utils
-        mount -t sysfs -o ro sysfs ${target}/sys
         echo "/dev/root / ext4 errors=remount-ro 0 1" > ${target}/etc/fstab
+        grep koji.softwarefactory-project.io /etc/hosts | sudo tee -a ${target}/etc/hosts > /dev/null || true
         checkpoint "first bootstrap"
     elif [ -f "${target}/usr/bin/yum-complete-transaction" ]; then
         do_chroot ${dir} yum-complete-transaction --cleanup-only
@@ -306,7 +313,7 @@ EOF
 
     # Update bundle; remove mysql2 gem because it might need to be rebuilt
     # against newer mariadb server
-    SUDO_UID=0 SUDO_GID=0 do_chroot ${dir} bash -c "cd /var/www/redmine/ && gem uninstall mysql2 && bundle update"
+    # SUDO_UID=0 SUDO_GID=0 do_chroot ${dir} bash -c "cd /var/www/redmine/ && gem uninstall mysql2 && bundle update"
 
     # Set files permissions (according to: http://www.redmine.org/projects/redmine/wiki/redmineinstall )
     mkdir -p ${dir}/var/www/redmine/{tmp,tmp/pdf,public/plugin_assets}
@@ -430,18 +437,111 @@ image_clean() {
 
 final_image_clean() {
     # Remove build-requirements package
-    do_chroot ${dir} yum remove -y ${BUILD_PKGS} &> /dev/null
+    # do_chroot ${dir} yum remove -y ${BUILD_PKGS} &> /dev/null
     rm -Rf ${dir}/usr/local/share/gems/cache ${dir}/usr/local/share/gems/doc
-    rm -Rf ${dir}/var/lib/yum/yumdb/*
+    # rm -Rf ${dir}/var/lib/yum/yumdb/*
     rm -Rf ${dir}/root/.cache
     rm -Rf ${dir}/root/.npm
     rm -Rf ${dir}/root/.gem
     rm -Rf ${dir}/root/.rpmdb
-    rm -Rf ${dir}/usr/src/
+    # rm -Rf ${dir}/usr/src/
 }
 
 fix_ansible_issue5504() {
     sed -i "s/after=remote_head, //" ${dir}/usr/lib/python2.7/site-packages/ansible/modules/core/source_control/git.py
+}
+
+function install_sf {
+    set -e
+    test -n "${CAUTH_CLONED_PATH}"
+    test -n "${MANAGESF_CLONED_PATH}"
+    test -n "${PYSFLIB_CLONED_PATH}"
+    test -n "${SFMANAGER_CLONED_PATH}"
+
+    mkdir -p ${dir}/usr/src
+
+    cp -f /etc/resolv.conf "${dir}/etc/"
+
+    if [ ! -z "${STAGING_PKGS}" ]; then
+        install_packages ${dir} ${STAGING_PKGS}
+    fi
+    if [ ! -z "${STAGING_PIP}" ]; then
+        retry do_chroot ${dir} pip install 'pip<8' ${STAGING_PIP}
+    fi
+
+    # Make sure subproject are available
+    if [ ! -d "${CAUTH_CLONED_PATH}" ] || [ ! -d "${MANAGESF_CLONED_PATH}" ] || \
+        [ ! -d "${PYSFLIB_CLONED_PATH}" ] || [ ! -d "${SFMANAGER_CLONED_PATH}" ]; then
+        echo "Can't find subprojects in $(dirname ${CAUTH_CLONED_PATH})"
+        echo "Run ./image/fetch_subprojects.sh first"
+        exit -1
+    fi
+
+    # Make sure final image use latest ids.tables
+    cp ./C7.0-ids.tables ${dir}/etc/ids.tables
+
+    # Disable postfix and remove configuration to reduce puppet noise
+    # Disable postfix and remove configuration
+    do_chroot ${dir} systemctl disable postfix
+    for i in main.cf virtual; do
+        echo -n > ${dir}/etc/postfix/$i
+    done
+
+    # Install ansible playbooks and configuration files
+    do_chroot ${dir} mkdir -p /etc/software-factory
+    sudo rsync --delete -a --no-owner ./../serverspec/ ${dir}/etc/serverspec/
+
+    # Sf-config
+    sudo rsync -a --no-owner ./../config/scripts/ ${dir}/usr/local/bin/
+    sudo rsync --delete -a -L --no-owner ./../config/defaults/ ${dir}/etc/software-factory/
+    sudo rsync --delete -a -L --no-owner ./../config/defaults/ ${dir}/usr/local/share/sf-default-config/
+    sudo rsync --delete -a --no-owner ./../config/ansible/ ${dir}/etc/ansible/
+    sudo mkdir -p ${dir}/etc/software-factory ${dir}/etc/ansible/group_vars ${dir}/var/lib/ansible
+    sudo rsync --delete -a --no-owner ./../health-check/ ${dir}/etc/ansible/health-check/
+
+    sudo cp -Rv ./../config/config-repo/ ${dir}/usr/local/share/sf-config-repo
+    sudo cp -Rv ./../tools/slaves/ ${dir}/usr/local/share/sf-jenkins-slave-tools
+    # Also copy tool in image PATH so that sf image could
+    # be used as slave base image
+    sudo cp -Rv ./../tools/slaves/* ${dir}/usr/local/bin/
+
+    # Install cauth
+    sudo rsync -a --delete ${CAUTH_CLONED_PATH}/ ${dir}/usr/src/cauth/
+    do_chroot ${dir} bash -c "cd /usr/src/cauth; /var/www/cauth/bin/python setup.py install"
+
+    # Install managesf
+    sudo rsync -a --delete ${MANAGESF_CLONED_PATH}/ ${dir}/usr/src/managesf/
+    do_chroot ${dir} bash -c "cd /usr/src/managesf; /var/www/managesf/bin/python setup.py install"
+
+    # Install python-sfmanager
+    sudo rsync -a --delete ${SFMANAGER_CLONED_PATH}/ ${dir}/usr/src/python-sfmanager/
+    do_chroot ${dir} bash -c "cd /usr/src/python-sfmanager; /srv/sfmanager/bin/python setup.py install --install-scripts /usr/bin"
+
+    # Install pysflib
+    sudo rsync -a --delete ${PYSFLIB_CLONED_PATH}/ ${dir}/usr/src/pysflib/
+    do_chroot ${dir} bash -c "cd /usr/src/pysflib; /var/www/cauth/bin/python setup.py install"
+    do_chroot ${dir} bash -c "cd /usr/src/pysflib; /var/www/managesf/bin/python setup.py install"
+    do_chroot ${dir} bash -c "cd /usr/src/pysflib; /srv/sfmanager/bin/python setup.py install"
+
+
+    do_chroot ${dir} find /root /var/www /srv/ -name "*.pyc" -exec rm {} \;
+
+    # Documentation
+    DOCBUILDDIR=$(mktemp -d /tmp/sfdocs_buildXXXXXXX)
+    rm -Rf ${dir}/var/www/docs
+    mkdir ${dir}/var/www/docs
+    cd ${DOCDIR} && make BUILDDIR=$DOCBUILDDIR MANAGESF_CLONED_PATH=${MANAGESF_CLONED_PATH} SFMANAGER_CLONED_PATH=${SFMANAGER_CLONED_PATH} html ; cd -
+    mv $DOCBUILDDIR/html/* ${dir}/var/www/docs/
+    rm -rf $DOCBUILDDIR
+
+    # Deactivate default disabling of root ssh access of cloud-init
+    sed -i 's/disable_root:.*/disable_root: 0/' ${dir}/etc/cloud/cloud.cfg
+
+    # Set a default password. This is needed when image is booted when metadata servers
+    # are not available. Cloudinit will deactivate root auth by password.
+    do_chroot ${dir} bash -c "passwd -d root"
+    # Be sure sshd disallow authentication by password (only allowed by key)
+    sed -i 's/^PasswordAuthentication.*/PasswordAuthentication no/' ${dir}/etc/ssh/sshd_config
 }
 
 START=$(date '+%s')
@@ -449,7 +549,7 @@ function checkpoint {
     set +x
     NOW=$(date '+%s')
     ELAPSED=$(python -c "print('%03.2fmin' % (($NOW - $START) / 60.0))")
-    echo "(STEP${STEP}) $ELAPSED - $*"
+    echo "(STEP1) $ELAPSED - $*"
     START=$(date '+%s')
     [ -z "${DEBUG}" ] || set -x
 }
@@ -463,7 +563,7 @@ fi
 check_binary yum
 check_binary rpm
 
-if [ "$STEP" == 1 ]; then
+build_all() {
     bootstrap
     checkpoint "bootstrapped"
     install_sf_packages
@@ -511,17 +611,11 @@ if [ "$STEP" == 1 ]; then
     ansible_install sf-job-logs-gearman-client "log_gearman_client_url: \"${LOG_GEARMAN_CLIENT_URL}\""
     ansible_install sf-job-logs-gearman-worker "log_gearman_worker_url: \"${LOG_GEARMAN_WORKER_URL}\""
     ansible_install sf-repoxplorer "$REPOXPLORER_EXTRA_VARS"
-    image_clean
-    do_chroot ${dir} passwd -l root
-    checkpoint "image cleaned"
-fi
-
-if [ "$STEP" == 2 ]; then
-    mount_fs
-    . sf.install
     install_sf
     checkpoint "sf installed"
     image_clean
     final_image_clean
     checkpoint "image cleaned"
-fi
+}
+
+build_all
